server:
  port: 8002

eureka:
  client:
    serviceUrl:
      defaultZone: http://192.168.99.100:8000/eureka/

feign:
  hystrix:
    enabled: true
  httpclient:
    connection-timeout: 30000


spring:
  sleuth:
    web:
      client:
        enabled: true
    sampler:
      probability: 1.0
  zipkin:
    base-url: http://192.168.99.100:9411
    discoveryClientEnabled: false
