server:
  port: 8003

spring:
  cloud:
    nacos:
      discovery:
        server-addr: 39.107.241.217:8848
    gateway:
      discovery:
        locator:
          lower-case-service-id: true
          enabled: true
      routes:
        - id: xcy-cloud-server
          uri: lb://xcy-cloud-server
          predicates:
            - Path=/user/**
          filters:
            - StripPrefix=1
  sleuth:
      web:
        client:
          enabled: true
      sampler:
        probability: 1.0
  zipkin:
      base-url: http://39.107.241.217:9411
      discoveryClientEnabled: false


