server:
  port: 8003

spring:
  cloud:
    gateway:
      discovery:
        locator:
          lower-case-service-id: true
          enabled: true
      routes:
        - id: xcy-cloud-server
          uri: lb://xcy-cloud-server
          predicates:
            - Path=/user/**
          filters:
            - StripPrefix=1
  sleuth:
      web:
        client:
          enabled: true
      sampler:
        probability: 1.0
  zipkin:
      base-url: http://192.168.99.100:9411
      discoveryClientEnabled: false
eureka:
  client:
    service-url:
      defaultZone: http://192.168.99.100:8000/eureka/

